version: '3.8'

services:
  carpool-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/carpool
      - SESSION_SECRET=your-session-secret
    depends_on:
      - mongo
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    networks:
      - carpool-network

  mongo:
    image: mongo:7
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: carpool
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - carpool-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - carpool-app
    restart: unless-stopped
    networks:
      - carpool-network

volumes:
  mongo_data:

networks:
  carpool-network:
    driver: bridge
